---
galaxy_info:
  author: "Attila van der Velde"
  description: "Extra Packages for Enterprise Linux (EPEL)"
  company: "PCextreme B.V."
  license: "license (MIT, BSD)"
  min_ansible_version: 1.8
  platforms:
    - name: EL
      versions:
        - 6
        - 7
  categories:
    - packaging

dependencies: []
