---
- name: Add Remi repo file
  template: src=remi.repo.j2 dest=/etc/yum.repos.d/remi.repo owner=root group=root mode=0644

- name: Add Remi repo key
  get_url: url=http://rpms.famillecollet.com/RPM-GPG-KEY-remi dest=/etc/pki/rpm-gpg/RPM-GPG-KEY-remi sha256sum=b0d1d4ca043e2bd60ff71899b5c0145af64f9c0ec6f2073357dfb64deada59e4 force=yes

- name: Add Remi repo key
  file: path=/etc/pki/rpm-gpg/RPM-GPG-KEY-remi owner=root group=root mode=0644

- name: Add Remi repo key
  rpm_key: state=present key=/etc/pki/rpm-gpg/RPM-GPG-KEY-remi
